# Generated by Django 5.1.3 on 2024-12-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=90)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('scaler_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timeslots', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('professor', 'Professor'), ('student', 'Student'), ('TA', 'Teacher Assistant')], max_length=10)),
                ('scaler_value', models.FloatField(default=1)),
                ('student_scaler', models.FloatField(default=1.0)),
                ('teacher_scaler', models.FloatField(default=10.0)),
                ('courses_as_student', models.ManyToManyField(related_name='cources_as_student', to='core.course')),
                ('courses_as_teacher', models.ManyToManyField(related_name='cources_as_teacher', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_in_minutes', models.IntegerField(default=90)),
                ('lesson_type', models.CharField(choices=[('normal', 'Normal Class'), ('tutorial', 'Tutorial'), ('extended', 'Extended Class')], max_length=10)),
                ('times_per_week', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course')),
            ],
        ),
    ]
