# Generated by Django 5.1.3 on 2024-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='timezone',
            field=models.IntegerField(default=6),
        ),
    ]
