# Generated by Django 5.0.6 on 2024-12-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_individual_alter_schedule_professor_delete_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('normal', 'Normal Class'), ('tutorial', 'Tutorial')], max_length=10)),
                ('times_per_week', models.IntegerField(default=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='course',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='scaler_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='individual',
            name='scaler_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course'),
        ),
    ]
